on:
  push:
    branches:
      - main

jobs:
  publish:
    runs-on: ubuntu-latest
    permissions:
      id-token: write
      contents: read
    steps:
      - uses: actions/checkout@3d3c42e5aac5ba805825da76410c181273ba90b1 # v7.0.1
        with:
          persist-credentials: false

      - uses: DeterminateSystems/determinate-nix-action@main

      - uses: DeterminateSystems/flakehub-cache-action@main

      - uses: DeterminateSystems/flakehub-push@main
        with:
          rolling: true
          visibility: public
